GET http://localhost:3001/api/v1/products
Content-Type: application/json

###

GET http://localhost:3001/api/v1/products?title=Eco-friendly Water Bottle 
Content-Type: application/json



###

GET http://localhost:3001/api/v1/products?pid=660de26374f431e4dc5faf55
Content-Type: application/json

###

GET http://localhost:3001/api/v1/products?categoryId=clothes
Content-Type: application/json

###

GET http://localhost:3001/api/v1/products?pid=6606af63515e82ab88828077
Content-Type: application/json

###

PUT http://localhost:3001/api/v1/products/6606af63515e82ab88828077
Content-Type: application/json

{
"title": "updated"
}

