openapi: 3.0.0
servers:
  - description: E-commerce website API
    url: http://localhost:3000
info:
  title: E-commerce API
  version: "1.0.0"
  description: This is an API for an e-commerce platform.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
paths:
  /products:
    get:
      summary: List all products
      tags: [Product]
      responses:
        "200":
          description: An array of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"
    post:
      summary: Create a new product
      tags: [Product]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"
      responses:
        "201":
          description: Product created

  /products/{productId}:
    get:
      summary: Get a product by ID
      tags: [Product]
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: A single product
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
    put:
      summary: Update a product
      tags: [Product]
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"
      responses:
        "200":
          description: Product updated
    delete:
      summary: Delete a product
      tags: [Product]
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: integer
      responses:
        "204":
          description: Product deleted

  /users:
    post:
      summary: Create a new user
      tags: [User]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        "201":
          description: User created

  /users/{userId}:
    get:
      summary: Get a user by ID
      tags: [User]
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: A single user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
    put:
      summary: Update a user
      tags: [User]
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        "200":
          description: User updated
    delete:
      summary: Delete a user
      tags: [User]
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
      responses:
        "204":
          description: User deleted

  /users/forget-password:
    post: 
      summary: Forget password
      tags: [Users]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ForgetPassword"
      responses:
        "200":
          description: Email sent

  /users/change-password:
    post:
      summary: Change user password
      tags: [Users]
      security:
        - jwtAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ChangePassword"
      responses:
        "200":
          description: Password changed

  /categories:
    get:
      summary: List all categories
      tags: [Categories]
      responses:
        "200":
          description: An array of categories
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Category"
    post:
      summary: Create a new category
      tags: [Categories]
      security:
        - adminAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Category"
      responses:
        "201":
          description: Category created

  /categories/{name}:
    get:
      summary: Get a category by name
      tags: [Categories]
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: A single category
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Category"
    put:
      summary: Update a category by name
      tags: [Categories]
      security:
        - adminAuth: []
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Category"
      responses:
        "200":
          description: Category updated
    delete:
      summary: Delete a category by name
      tags: [Categories]
      security:
        - adminAuth: []
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
      responses:
        "204":
          description: Category deleted

  /orderItems:
    post:
      summary: Create a new order item
      tags: [OrderItems]
      security:
        - jwtAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OrderItem"
      responses:
        "201":
          description: Order item created
    get:
      summary: List all order items
      tags: [OrderItems]
      security:
        - jwtAuth: []
      responses:
        "200":
          description: An array of order items
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/OrderItem"
                  
  /orderItems/{orderItemId}:
    put:
      summary: Update an order item's quantity
      tags: [OrderItems]
      security:
        - jwtAuth: []
      parameters:
        - name: orderItemId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OrderItemQuantityUpdate"
      responses:
        "200":
          description: Order item quantity updated
    get:
      summary: Get an order item by ID
      tags: [OrderItems]
      security:
        - jwtAuth: []
      parameters:
        - name: orderItemId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: A single order item
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OrderItem"
    delete:
      summary: Delete an order item by ID
      tags: [OrderItems]
      security:
        - jwtAuth: []
      parameters:
        - name: orderItemId
          in: path
          required: true
          schema:
            type: string
      responses:
        "204":
          description: Order item deleted
  /orders:
    post:
      summary: Create a new order
      tags: [Orders]
      security:
        - jwtAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Order"
      responses:
        "201":
          description: Order created
    get:
      summary: List all orders
      tags: [Orders]
      security:
        - jwtAuth: []
      responses:
        "200":
          description: An array of orders
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Order"
  /orders/{orderId}:
    get:
      summary: Get an order by ID
      tags: [Orders]
      security:
        - jwtAuth: []
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: A single order
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"
    put:
      summary: Update an order
      tags: [Orders]
      security:
        - jwtAuth: []
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Order"
      responses:
        "200":
          description: Order updated
    delete:
      summary: Delete an order by ID
      tags: [Orders]
      security:
        - jwtAuth: []
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: string
      responses:
        "204":
          description: Order deleted
components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Unique identifier for the product
        name:
          type: string
          description: Name of the product
        price:
          type: number
          format: float
          description: Price of the product
        inStock:
          type: boolean
          description: Availability of the product
    Category:
      type: object
      properties:
        name:
          type: string
    OrderItem:
      type: object
      properties:
        id:
          type: integer
        orderId:
          type: integer
        productId:
          type: integer
        quantity:
          type: integer
    OrderItemQuantityUpdate:
      type: object
      properties:
        quantity:
          type: integer
    Order:
      type: object
      properties:
        id:
          type: integer
        status:
          type: string
        items:
          type: array
          items:
            $ref: '#/components/schemas/OrderItem'
    ForgetPassword:
      type: object
      properties:
        email:
          type: string
          format: email
    ChangePassword:
      type: object
      properties:
        oldPassword:
          type: string
        newPassword:
          type: string
