POST http://localhost:3001/api/v1/categories 
Content-Type: application/json

{
"_id": "books"
}

###

PUT http://localhost:3001/api/v1/categories/misc
Content-Type: application/json

{
"createdAt": "2024-04-04T12:24:48.922Z"
}
